animals_list = ['aardvark', 'adder', 'agouti', 'akita', 'albatross', 'alligator', 'alpaca',
                        'amphibian', 'anaconda', 'angelfish', 'anole', 'ant', 'anteater', 'antelope',
                        'antlion', 'aoudad', 'ape', 'aphid', 'arachnid', 'argali', 'armadillo', 'armet',
                        'avocet', 'axolotl', 'babirusa', 'baboon', 'badelfish', 'badger', 'barbet',
                        'barracuda', 'basilisk', 'bass', 'bat', 'batfish', 'bear', 'beast', 'beaver',
                        'bee', 'beetle', 'beluga', 'betta', 'bichon', 'binturong', 'bird', 'bison',
                        'bluefish', 'bluejay', 'boa', 'boar', 'booby', 'boto', 'boxer', 'bream', 'buck',
                        'budgerigar', 'buffalo', 'bug', 'bulbul', 'bullfrog', 'bumblebee', 'bunting',
                        'bushbaby', 'butterfly', 'buzzard', 'caiman', 'camel', 'canary', 'capybara',
                        'caracal', 'cardinal', 'caribou', 'carp', 'cassowary', 'cat', 'catbird',
                        'caterpillar', 'catfish', 'cattle', 'centipede', 'chameleon', 'chamois',
                        'chaparral', 'cheetah', 'chickadee', 'chicken', 'chihuahua', 'chimpanzee',
                        'chinchbug', 'chinchilla', 'chipmunk', 'chital', 'chough', 'chow', 'cicada',
                        'civet', 'clam', 'coati', 'cobra', 'cockatiel', 'cockatoo', 'cockroach', 'cod',
                        'codfish', 'collie', 'conch', 'condor', 'conure', 'coot', 'copperhead', 'coral',
                        'cormorant', 'cottonmouth', 'cougar', 'cowbird', 'coyote', 'crab', 'crane',
                        'crappie', 'cricket', 'crocodile', 'crossbill', 'crow', 'cuckoo', 'cur',
                        'curassow', 'curlew', 'cuscus', 'cuttlefish', 'dachshund', 'dalmatian',
                        'damselfly', 'danio', 'dartfish', 'deer', 'dhole', 'dingo', 'dinosaur',
                        'doberman', 'dodo', 'dog', 'dolphin', 'donkey', 'dormouse', 'dotterel', 'dove',
                        'dovekie', 'dragon', 'dragonfly', 'drongo', 'drum', 'duck', 'dugong', 'dunlin',
                        'dunnock', 'eagle', 'earthworm', 'earwig', 'echidna', 'eel', 'egret', 'eider',
                        'eland', 'elephant', 'elk', 'elver', 'emu', 'enhydra', 'ermine',
                        'falcon', 'ferret', 'finch', 'firefly', 'fish', 'flamingo', 'flatfish', 'flea',
                        'flicker', 'fly', 'flycatcher', 'flyingfish', 'fossa', 'fox', 'frigatebird',
                        'frog', 'fulmar', 'galago', 'gallinule', 'gander', 'gar', 'garpike',
                        'gaur', 'gazelle', 'gecko', 'gelada', 'gerbil', 'gharial', 'gibbon', 'giraffe',
                        'glaucous', 'gnat', 'gnatcatcher', 'gnu', 'goat', 'goatfish', 'goby', 'goldeneye',
                        'goldfinch', 'goldfish', 'goosander', 'goose', 'goosefish', 'gopher', 'gorilla',
                        'goshawk', 'grackle', 'grasshopper', 'grayling', 'greenfinch', 'greenshank',
                        'grouse', 'grub', 'guan', 'guanaco', 'guenon', 'gull', 'guppy', 'haddock',
                        'halcyon', 'halibut', 'hamster', 'hare', 'harrier', 'hartebeest', 'hawk',
                        'hedgehog', 'heron', 'herring', 'hippopotamus', 'honeyeater', 'hookworm', 'hoopoe',
                        'hornbill', 'hornet', 'horse', 'horsefly', 'hound', 'housefly', 'hoverfly',
                        'human', 'hummingbird', 'hyena', 'ibex', 'ibis', 'ichneumon', 'iguana', 'impala',
                        'indigo', 'indris', 'insect', 'jackal', 'jackrabbit', 'jaguar', 'jaguarundi',
                        'jay', 'jellyfish', 'jennet', 'jerboa', 'junglefowl', 'kagu', 'kakapo', 'kangaroo',
                        'karakul', 'keeshond', 'kelpie', 'kennet', 'kentish', 'kestrel', 'killdeer',
                        'kingbird', 'kingfisher', 'koala', 'koi', 'dragon', 'kookaburra', 'kouprey',
                        'kudu', 'labrador', 'lapwing', 'lark', 'lemming', 'lemur', 'leopard', 'limpet',
                        'linnet', 'lion', 'lionfish', 'lizard', 'llama', 'lobster', 'locust', 'loon',
                        'loris', 'louse', 'lynx', 'lyrebird', 'macaque', 'macaw', 'mackerel', 'magpie',
                        'mallard', 'mammal', 'mammoth', 'manatee', 'mandrill', 'ray', 'mantis', 'marlin',
                        'marmoset', 'marten', 'mastiff', 'mayfly', 'meadowlark', 'meerkat', 'millipede',
                        'mink', 'minnow', 'mockingbird', 'mole', 'mongoose', 'mongrel', 'monkey', 'moorhen',
                        'moose', 'moray', 'mosquito', 'moth', 'mouflon', 'mouse',
                        'mousebird', 'mudskipper', 'mule', 'narwhal', 'nase', 'newfoundland', 'newt',
                        'nightcrawler', 'nightfish', 'nightingale', 'nuthatch', 'nyala', 'oakworm',
                        'ocelot', 'octopus', 'okapi', 'olm', 'opossum', 'orangutan', 'oriole', 'osprey',
                        'ostrich', 'otter', 'ouzel', 'ovenbird', 'owl', 'ox', 'oxpecker', 'oyster', 'paca',
                        'packrat', 'pademelon', 'panda', 'panther', 'parakeet', 'parrot', 'parrotfish',
                        'partridge', 'peacock', 'peafowl', 'peccary', 'pelican', 'penguin', 'perch',
                        'pheasant', 'pig', 'pigeon', 'pika', 'pike', 'pilchard', 'pinniped', 'piranha',
                        'plankton', 'platyfish', 'platypus', 'plover', 'polecat', 'polliwog',
                        'pony', 'pooch', 'poodle', 'porcupine', 'porgy', 'porpoise', 'possum', 'potto',
                        'prawn', 'pufferfish', 'puffin', 'puma', 'quail', 'quelea', 'quetzal', 'quokka',
                        'quoll', 'rabbit', 'raccoon', 'ragworm', 'rail', 'ram', 'rat', 'ratfish',
                        'rattlesnake', 'raven', 'reindeer', 'reptile', 'rhino', 'rhinoceros', 'robin',
                        'rockfish', 'rodent', 'roller', 'rook', 'rooster', 'rottweiler', 'sable',
                        'salamander', 'salmon', 'dollar', 'sandpiper', 'sardine', 'scallop', 'scarab',
                        'scorpion', 'seagull', 'seahawk', 'seahorse', 'seal', 'serpent', 'setter', 'shark',
                        'shearwater', 'sheep', 'shelduck', 'shrew', 'shrimp', 'siamang', 'siamese',
                        'silverfish', 'skate', 'skimmer', 'skink', 'skipjack', 'skunk', 'sloth', 'slug',
                        'snail', 'snake', 'snapper', 'sparrow', 'spider', 'spoonbill',
                        'springbok', 'squid', 'squirrel', 'starfish', 'starling', 'stingray', 'stinkbug',
                        'stoat', 'stork', 'sunfish', 'swallow', 'swan', 'tamarin', 'tanager', 'tapeworm',
                        'tapir', 'tarantula', 'tarpon', 'tarsier', 'teal', 'termite', 'tetra', 'tiger',
                        'tigerfish', 'toad', 'toucan', 'trout', 'tuna', 'turbot', 'turkey', 'turtle',
                        'uakari', 'uguisu', 'urchin', 'vulture', 'wallaby', 'walleye',
                        'walrus', 'warbler', 'warthog', 'wasp', 'weasel', 'whale', 'whippet', 'whitefish',
                        'wildcat', 'wildebeest', 'wolf', 'wombat', 'woodchuck', 'woodcock', 'woodpecker',
                        'worm', 'wrasse', 'wren', 'yabby', 'yak', 'yellowjacket', 'zebra', 'zebu', 'zonkey',
                        'zooplankton']


for animal in animals_list:
    if " " in animal:
        print(animal)
